### ISSUE TITLE
Challenge Achieved Alhamdulillah !

### ISSUE THREAD

**Issue by Ghazanfar373** [KhaledAlharthi/HarajAndroidChallenge#4]
Here is details
https://github.com/Ghazanfar373/My_Application

Here is Demo
https://youtu.be/FWZ0fccpNHs

**Comment by KhaledAlharthi** [comment]
Best of luck brother!

**Comment by Ghazanfar373** [comment]
> Best of luck brother!

Actually I'm a big fan of Haraj.com, like it helps to find me a good car. As a software engineer I was feeling if there is a chance then I would like to share my expertise to make this platform better by good software practices! Looking forward for your kind reply!
